# @package hydra.launcher
account: rrg-bengioy-ad  #rrg-lpaull
# partition: long
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher # hydra_plugins.packed_launcher.packedlauncher.SlurmLauncher
cpus_per_task: 6
mem_gb: 128
tasks_per_node: 1
stderr_to_stdout: False
#gres: gpu:l40s:1 #gpu:32gb:1 # gpu:rtx8000:1 # No MIG: gpu:32gb:1
gres: gpu:nvidia_h100_80gb_hbm3_3g.40gb:1 # gpu:h100:1
submitit_folder: ${hydra.sweep.dir}/submitit/%j
#timeout_min: 1440 # 2 days: 2880 ; 12h : 720 ; 1 day: 1440
nodes: 1
name: ${hydra.job.name}
array_parallelism: 999 # max num of tasks to run in parallel (via job array)
#additional_parameters:
#  exclude: "fc10901,fc10713"
setup:
  - "export WANDB_DIR=${hydra.sweep.dir}"
  - "export HYDRA_SWEEP_DIR=${hydra.sweep.dir}"
  - "export BREAK=False"
  - "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/cgauthie/.mujoco/mujoco200/bin"
  # - 'export WANDB_MODE="offline"'
  - 'export WANDB_API_KEY="${secrets.wandb_key}"'
  - "export WANDB_INIT_TIMEOUT=600"
  - 'export TQDM_DISABLE=1'
  - "module load python/3.10"
  - "module load cuda/12.6"
  - "module load cudnn/9.5.1.17"
  #- "module load libffi"
  #- 'mkdir -p "/tmp/unimals_100"'
  #- 'find "/home/cgauthie/projects/def-lpaull/cgauthie/ModuMorph/unimals_100" -mindepth 1 -maxdepth 1 -print0 | xargs -0  -P1 -I% rsync --quiet -Pa % "/tmp/unimals_100"'
  - 'mkdir -p "$SLURM_TMPDIR/embodiment-scaling-laws/logs/rsl_rl"'
  - 'mkdir -p "/tmp/embodiment-scaling-laws/logs"'
  #- 'cp -r /network/scratch/c/charlie.gauthier/embodiment-scaling-laws /tmp/esl'
  - "echo \"[$(date '+%Y-%m-%d %H:%M:%S')] Syncing training data from ${oc.env:SCRATCH}/embodiment-scaling-laws/logs/rsl_rl to $SLURM_TMPDIR/embodiment-scaling-laws/logs/rsl_rl\""
  - 'find "${oc.env:SCRATCH}/embodiment-scaling-laws/logs/rsl_rl" -mindepth 1 -maxdepth 1 -print0 | xargs -0 -P32 -I% rsync --quiet -Pa % "$SLURM_TMPDIR/embodiment-scaling-laws/logs/rsl_rl"'
  - 'ln -s  $SLURM_TMPDIR/embodiment-scaling-laws/logs/rsl_rl /tmp/embodiment-scaling-laws/logs/rsl_rl'
  - '[ -L /tmp/embodiment-scaling-laws/logs/rsl_rl ] || { echo "ERROR: symlink creation failed"; exit 1; }'
  - 'ls /tmp/embodiment-scaling-laws/logs/rsl_rl | head -10'
  #- >-
  #  find "${oc.env:SCRATCH}/embodiment-scaling-laws/logs/rsl_rl" -mindepth 1 -maxdepth 1 -print0 |
  #  xargs -0 -P16 -I% bash -c 'd=$(basename "$1") && mkdir -p "/tmp/embodiment-scaling-laws/logs/rsl_rl/$d" && tar -C "$1" -cf - . | tar -C "/tmp/embodiment-scaling-laws/logs/rsl_rl/$d" -xpf -' _ %
  - "echo \"[$(date '+%Y-%m-%d %H:%M:%S')] Done syncing training data\""
  - "source /home/cgauthie/projects/def-lpaull/cgauthie/embodiment-scaling-laws/env_isaaclab/bin/activate"
  - "sleep $((RANDOM % 100))"
  - "echo Starting Training Now..."

# module load cuda/12.1.1/cudnn
# module load python/3.10
#  python3.9 -m pip install --upgrade "jaxlib==0.4.13+cuda11.cudnn86" "jax[cuda11_pip]==0.4.13" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html --no-cache
# pip3 install -r requirements.txt
# pip3 install flax==0.7.4
#  python3.9 -m pip install --upgrade "jaxlib[cuda11_pip]==0.4.13" "jax[cuda11_pip]==0.4.13" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html --no-cache
# pip install hydra-submitit-launcher --upgrade
# python3 main.py --multirun hydra/launcher=sbatch +hydra/sweep=sbatch wandb.seed=1,2
# python3 main.py --multirun hydra/launcher=sbatch +hydra/sweep=sbatch sim=sim10k_10000 wandb.seed=1,2,3,4,5 sim.bad_init=False,True dist=four_bananas,rastrigin10d,rastrigin2d,michalewicz10d,michalewicz2d,five_mvn_dim10,rosenbrock10d,rosenbrock2d adapt=indep,mape_single,mape_test,haario,random_walk,mala wandb.project=milaclustermbrma


#   - 'export WANDB_WATCH="false"'
#  - 'export WANDB__SERVICE_WAIT=300'
 # - 'export WANDB_MODE="offline"'
#

