# Hydra configuration for run_distillation.py
# Use with: python run_distillation.py --config-name=config
# Or call hydra_main() directly for hydra-submitit

defaults:
  - meta: default
  - optim: e10_lr3e-4_acc1
  - dataloading: bs256_mem1_env512_rep1
  - ablation: no_bboxes
  - _self_
  - secrets: secrets

meta:
  run_name: my_experiment
resume: null
train_set:
- robot1
- robot2
test_set: []
